name = "Fabric Viva Minecraft"
author = "Miguel"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f8d9dd1dae640361fe103e8e33c1838c895854ee20bb23a45b32144f557262b"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
